{% set name = "gnupg" %}
{% set version = "2.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: dd17ab2e9a04fd79d39d853f599cbc852062ddb9ab52a4ddeb4176fd8b302964

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gnupg', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
  host:
    - npth {{ npth }}
    - libgpg-error {{ libgpg_error }}
    - libgcrypt {{ libgcrypt }}
    - libksba {{ libksba }}
    - libassuan {{ libassuan }}
    - pinentry 1.3.1
    - sqlite {{ sqlite }}
    - ntbtls {{ ntbtls}}
    - libiconv {{ libiconv}}
    - readline {{ readline }}
    - zlib {{ zlib }}

test:
  commands:
    - gpg --help

about:
  home: https://www.gnupg.org
  doc_url: https://www.gnupg.org
  dev_url: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git
  summary: The GNU Privacy Guard
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  description: |
    GnuPG is a complete and free implementation of the OpenPGP standard as defined
    by RFC4880 (also known as PGP). GnuPG allows you to encrypt and sign your data
    and communications; it features a versatile key management system, along with
    access modules for all kinds of public key directories. GnuPG, also known as GPG,
    is a command line tool with features for easy integration with other applications.
    A wealth of frontend applications and libraries are available. GnuPG also provides
    support for S/MIME and Secure Shell (ssh).

extra:
  recipe-maintainers:
    - mariusvniekerk
