travis:
  secure:
    BINSTAR_TOKEN: Y58btOwSNTJl6xwBenkpDsPfImTqOPDzyIyGTAwxO0PFUCzu525us3HrQv5rNAL0icFyAdojwxuitk9Cehn/L6s/cLhf0MX2c2zcfZIV+lmxmK3iLa/FbKf085dQPqCz+aPC7wuFp/2qSSd+6563hDtXOu6wO59m7PaEH5/M8azlE7BAXKxJQ7XUF+oDtwS/aJ2VPYEebW/21GKd6V5ffdZ+jvTd+iWk4oIhSFuEMTocxHb7EDUoHlm2hxPgJIibsYDiI5ZPttVHG9Ps3MivELr9VLUBvi4hZXZgv+cnJwrVY9j2hqX/8EK+O19p5bQscf+SD9SCRoy38FraPK8MUD4VvrIl84FI6D2WfPa5zEwmUjb0JYjnotYRn/oDe5TYN6ogCc1HcyB5nzdhudTOXNuf0XattW7dkVNUyr8dsOhVOpFC3ooBwIz9Yc2JJjEaDVmC/doIh2+ePuS49+mRstgQXIp1mPwdZfRxew0AqjCEfb/ys0pIl1ZkheLqkOYMA/b2PPJlsFOK70kIg8mmhR2fOF1xx5P8Fzr7QiTiZPmS7zSyXzv5KJuON0gO5RHwZDkhSxc8u1FEsGifFfQETp7VCEXS7qV8QlRRz5qHfwClPw5gdfumTloUatnPc5d9mvCzDnLZX0qwJ6wxd1hFD4nnWBg6JWR14d5ci0G1Iig=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
