travis:
  secure:
    BINSTAR_TOKEN: 19isQ1nC7CKYzQzgm4rwIvun5ddIpys6sHbusXtIUHLY+wr7SjUJ5e1XiG3221vnIglH0dGYpTUUxwT3dzUTOOemHYnfR0oZld18fRS38O1ktffRo3XPsq8FVmn0HEnDVPecd9/qRWSiirzFK97Vv7JjtKjF2mhTBgF3rJg+C47RXqurwAyHFbyBiinG7jY4zx6Q8Ine0RcWePP4hzq1DL1djN6YGVfiZOK6m8fHVabNIovDm1e1l08Ozk5ZYnbFeOMWzX4l+UYZAXoj8lY9VIK/DLgYKTmI+RgfHv5C/36+/RO+exwha7vuacE2JkNIDVpDDYVFwdKV97muejB1f43LYmsIr4y/nAInvE9ZjiZ2kP2wabzGsF8eVv9kvSxHjCtUdxj33Qot3VYQ5o/tnStfIUpWZHCyRlmOaKEba4Lh8wozI0dU6hSaEtc0yfbmZaFs5N7tc9GE7PfsVAHtxUVLGI9Y1jLFIZez1vcJ4ZzPqp2488BT1cYA/ryKV+MGByMsaD8cufX1ShF3ERNmjjkiFD1kDIyMC4RquApIb8FcXPW5S24fXU5eB0S2uLVQKJJBGNkvc0T1Rn996Irasn4gJUeLl/1/lEk/BodMwHq3ilBmjhqFPJ/6hnmTwXiHDUKOwEYROOvmq7R74YhDZkAdFWvqa0r4zPT9hnia8F4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
